### ISSUE TITLE
有灵缇加速的包么？

### ISSUE THREAD

**Issue by sorson** [liuran001/openwrt-packages#12]
在别的固件看到过，但找不到包

**Comment by liuran001** [comment]
稍等等下添加

**Comment by liuran001** [comment]
[已加入](https://github.com/liuran001/openwrt-packages/tree/packages/luci-app-LingTiGameAcc)

**Comment by sorson** [comment]
./scripts/feeds update -a
./scripts/feeds install -a
安装后提示
Installing package 'luci-app-LingTiGameAcc' from liuran001_packages
WARNING: No feed for package 'LingTiGameAcc' found

**Comment by liuran001** [comment]
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> 安装后提示
> Installing package 'luci-app-LingTiGameAcc' from liuran001_packages
> WARNING: No feed for package 'LingTiGameAcc' found

@sorson 现在可以了

**Comment by sorson** [comment]
LuCI >  Applications
找不到 LingTiGameAcc ,Feed里面也只留了你这个git

**Comment by liuran001** [comment]
> LuCI > Applications
> 找不到 LingTiGameAcc ,Feed里面也只留了你这个git

@sorson LingTiGameAcc是二进制文件，不在luci里面，是luci-app-LingTiGameAcc的依赖，加入luci-app-LingTiGameAcc之后会自动加入LingTiGameAcc
另外，默认的feed肯定要留着的，只留这一个肯定没法用😂

**Comment by liuran001** [comment]
你自己试吧，可以了再把issue关掉

**Comment by sorson** [comment]
> > LuCI > Applications
> > 找不到 LingTiGameAcc ,Feed里面也只留了你这个git
> 
> @sorson LingTiGameAcc是二进制文件，不在luci里面，是luci-app-LingTiGameAcc的依赖，加入luci-app-LingTiGameAcc之后会自动加入LingTiGameAcc
> 另外，默认的feed肯定要留着的，只留这一个肯定没法用😂

是在 make menuconfig后 LuCI > Applications里面也不见 luci-app-LingTiGameAcc，这是正常的？
但同类UU或3GINFO的插件是能看到的

**Comment by liuran001** [comment]
> > > LuCI > Applications
> > > 找不到 LingTiGameAcc ,Feed里面也只留了你这个git
> > 
> > 
> > @sorson LingTiGameAcc是二进制文件，不在luci里面，是luci-app-LingTiGameAcc的依赖，加入luci-app-LingTiGameAcc之后会自动加入LingTiGameAcc
> > 另外，默认的feed肯定要留着的，只留这一个肯定没法用😂
> 
> 是在 make menuconfig后 LuCI > Applications里面也不见 luci-app-LingTiGameAcc，这是正常的？
> 但同类UU或3GINFO的插件是能看到的

@sorson  不正常，你重新拉一遍源码看看

**Comment by sorson** [comment]
已解决，谢谢！
