### ISSUE TITLE
请问luci-app-ssr-plus的上游源码是来自哪里？

### ISSUE THREAD

**Issue by chika0801** [liuran001/openwrt-packages#21]
请问一下这个插件，没搜到上游到底是哪位大神在维护。

如果能告诉一下最好。感谢。

**Comment by ergdfrte** [comment]
不重要不重要

**Comment by chika0801** [comment]
> 不重要不重要

https://github.com/fw876/helloworld/commits/master

在TG群问到了，编译固件时用得到
