### ISSUE TITLE
WARNING: No feed for package 'tcpping' found WARNING: No feed for package 'microsocks' found WARNING: No feed for package 'dnscrypt-proxy-full' found WARNING: No feed for package 'dnsforwarder' found WARNING: No feed for package 'udpspeeder' found WARNING: No feed for package 'udp2raw-tunnel' found

### ISSUE THREAD

**Issue by vleboy** [liuran001/openwrt-packages#5]
WARNING: No feed for package '3ginfo-text' found
WARNING: No feed for package 'luci-app-modeminfo' found
WARNING: No feed for package 'pcap-dnsproxy' found
WARNING: No feed for package 'microsocks' found
WARNING: No feed for package 'redsocks2' found
WARNING: No feed for package 'tcpping' found
WARNING: No feed for package 'microsocks' found
WARNING: No feed for package 'dnscrypt-proxy-full' found
WARNING: No feed for package 'dnsforwarder' found
WARNING: No feed for package 'udpspeeder' found
WARNING: No feed for package 'udp2raw-tunnel' found

**Comment by liuran001** [comment]
等下加上

**Comment by liuran001** [comment]
加上了[https://github.com/liuran001/openwrt-packages_action/commit/21a76dfbfe62f9179aabe962e5405c7ed27fdbc1](https://github.com/liuran001/openwrt-packages_action/commit/21a76dfbfe62f9179aabe962e5405c7ed27fdbc1)
