### ISSUE TITLE
哈哈，可惜用不了

### ISSUE THREAD

**Issue by coLATin** [liuran001/openwrt-packages#6]
Create index file './feeds/liuran001_packages.index' 
ERROR: please fix feeds/liuran001_packages/GoQuiet/Makefile - see logs/feeds/liuran001_packages/GoQuiet/dump.txt for details
ERROR: please fix feeds/liuran001_packages/UnblockNeteaseMusicGo/Makefile - see logs/feeds/liuran001_packages/UnblockNeteaseMusicGo/dump.txt for details
ERROR: please fix feeds/liuran001_packages/frp/Makefile - see logs/feeds/liuran001_packages/frp/dump.txt for details
ERROR: please fix feeds/liuran001_packages/gost/Makefile - see logs/feeds/liuran001_packages/gost/dump.txt for details
ERROR: please fix feeds/liuran001_packages/kcptun/Makefile - see logs/feeds/liuran001_packages/kcptun/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-3ginfo/Makefile - see logs/feeds/liuran001_packages/luci-app-3ginfo/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-adbyby-plus/Makefile - see logs/feeds/liuran001_packages/luci-app-adbyby-plus/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-advancedsetting/Makefile - see logs/feeds/liuran001_packages/luci-app-advancedsetting/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-airplay2/Makefile - see logs/feeds/liuran001_packages/luci-app-airplay2/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-aliddns/Makefile - see logs/feeds/liuran001_packages/luci-app-aliddns/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-atinout/Makefile - see logs/feeds/liuran001_packages/luci-app-atinout/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-baidupcs-web/Makefile - see logs/feeds/liuran001_packages/luci-app-baidupcs-web/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-brook-server/Makefile - see logs/feeds/liuran001_packages/luci-app-brook-server/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-chinadns-ng/Makefile - see logs/feeds/liuran001_packages/luci-app-chinadns-ng/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-cifs-mount/Makefile - see logs/feeds/liuran001_packages/luci-app-cifs-mount/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-control-timewol/Makefile - see logs/feeds/liuran001_packages/luci-app-control-timewol/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-control-webrestriction/Makefile - see logs/feeds/liuran001_packages/luci-app-control-webrestriction/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-control-weburl/Makefile - see logs/feeds/liuran001_packages/luci-app-control-weburl/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-dockerman/Makefile - see logs/feeds/liuran001_packages/luci-app-dockerman/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-eqos/Makefile - see logs/feeds/liuran001_packages/luci-app-eqos/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-fileassistant/Makefile - see logs/feeds/liuran001_packages/luci-app-fileassistant/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-filebrowser/Makefile - see logs/feeds/liuran001_packages/luci-app-filebrowser/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-frpc/Makefile - see logs/feeds/liuran001_packages/luci-app-frpc/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-frps/Makefile - see logs/feeds/liuran001_packages/luci-app-frps/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-gost/Makefile - see logs/feeds/liuran001_packages/luci-app-gost/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-guest-wifi/Makefile - see logs/feeds/liuran001_packages/luci-app-guest-wifi/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-ipsec-vpnserver-manyusers/Makefile - see logs/feeds/liuran001_packages/luci-app-ipsec-vpnserver-manyusers/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-iptvhelper/Makefile - see logs/feeds/liuran001_packages/luci-app-iptvhelper/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-kcptun/Makefile - see logs/feeds/liuran001_packages/luci-app-kcptun/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-kodexplorer/Makefile - see logs/feeds/liuran001_packages/luci-app-kodexplorer/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-modeminfo/Makefile - see logs/feeds/liuran001_packages/luci-app-modeminfo/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-nodogsplash/Makefile - see logs/feeds/liuran001_packages/luci-app-nodogsplash/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-oaf/Makefile - see logs/feeds/liuran001_packages/luci-app-oaf/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-pcap-dnsproxy/Makefile - see logs/feeds/liuran001_packages/luci-app-pcap-dnsproxy/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-pppoe-relay/Makefile - see logs/feeds/liuran001_packages/luci-app-pppoe-relay/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-pppoe-server/Makefile - see logs/feeds/liuran001_packages/luci-app-pppoe-server/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-pptp-vpnserver-manyusers/Makefile - see logs/feeds/liuran001_packages/luci-app-pptp-vpnserver-manyusers/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-ramfree/Makefile - see logs/feeds/liuran001_packages/luci-app-ramfree/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-smartdns/Makefile - see logs/feeds/liuran001_packages/luci-app-smartdns/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-socat/Makefile - see logs/feeds/liuran001_packages/luci-app-socat/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-softethervpn/Makefile - see logs/feeds/liuran001_packages/luci-app-softethervpn/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-ssr-libev-server/Makefile - see logs/feeds/liuran001_packages/luci-app-ssr-libev-server/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-ssr-mudb-server/Makefile - see logs/feeds/liuran001_packages/luci-app-ssr-mudb-server/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-ssr-plus/Makefile - see logs/feeds/liuran001_packages/luci-app-ssr-plus/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-syncthing/Makefile - see logs/feeds/liuran001_packages/luci-app-syncthing/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-tcpdump/Makefile - see logs/feeds/liuran001_packages/luci-app-tcpdump/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-timecontrol/Makefile - see logs/feeds/liuran001_packages/luci-app-timecontrol/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-trojan-server/Makefile - see logs/feeds/liuran001_packages/luci-app-trojan-server/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-ttyd/Makefile - see logs/feeds/liuran001_packages/luci-app-ttyd/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-unblockmusic/Makefile - see logs/feeds/liuran001_packages/luci-app-unblockmusic/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-usb-printer/Makefile - see logs/feeds/liuran001_packages/luci-app-usb-printer/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-v2ray-server/Makefile - see logs/feeds/liuran001_packages/luci-app-v2ray-server/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-verysync/Makefile - see logs/feeds/liuran001_packages/luci-app-verysync/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-vlmcsd/Makefile - see logs/feeds/liuran001_packages/luci-app-vlmcsd/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-app-vsftpd/Makefile - see logs/feeds/liuran001_packages/luci-app-vsftpd/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-lib-docker/Makefile - see logs/feeds/liuran001_packages/luci-lib-docker/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-Butterfly/Makefile - see logs/feeds/liuran001_packages/luci-theme-Butterfly/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-Butterfly-dark/Makefile - see logs/feeds/liuran001_packages/luci-theme-Butterfly-dark/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argon/Makefile - see logs/feeds/liuran001_packages/luci-theme-argon/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argon-lr/Makefile - see logs/feeds/liuran001_packages/luci-theme-argon-lr/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argon-mc/Makefile - see logs/feeds/liuran001_packages/luci-theme-argon-mc/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argon-mod/Makefile - see logs/feeds/liuran001_packages/luci-theme-argon-mod/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argon_new/Makefile - see logs/feeds/liuran001_packages/luci-theme-argon_new/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argonv2/Makefile - see logs/feeds/liuran001_packages/luci-theme-argonv2/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-argonv3/Makefile - see logs/feeds/liuran001_packages/luci-theme-argonv3/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-atmaterial/Makefile - see logs/feeds/liuran001_packages/luci-theme-atmaterial/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-darkmatter/Makefile - see logs/feeds/liuran001_packages/luci-theme-darkmatter/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-edge/Makefile - see logs/feeds/liuran001_packages/luci-theme-edge/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-infinityfreedom/Makefile - see logs/feeds/liuran001_packages/luci-theme-infinityfreedom/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-netgearv2/Makefile - see logs/feeds/liuran001_packages/luci-theme-netgearv2/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-opentomato/Makefile - see logs/feeds/liuran001_packages/luci-theme-opentomato/dump.txt for details
ERROR: please fix feeds/liuran001_packages/luci-theme-rosy/Makefile - see logs/feeds/liuran001_packages/luci-theme-rosy/dump.txt for details
ERROR: please fix feeds/liuran001_packages/trojan-go/Makefile - see logs/feeds/liuran001_packages/trojan-go/dump.txt for details
ERROR: please fix feeds/liuran001_packages/v2ray/Makefile - see logs/feeds/liuran001_packages/v2ray/dump.txt for details
ERROR: please fix feeds/liuran001_packages/v2ray-plugin/Makefile - see logs/feeds/liuran001_packages/v2ray-plugin/dump.txt for details

**Comment by liuran001** [comment]
上日志

`see logs/feeds/liuran001_packages/XXX/dump.txt for details`
