### ISSUE TITLE
argeo主题

### ISSUE THREAD

**Issue by iancchiu** [liuran001/openwrt-packages#8]
argeo主题包太多了，分不清版本，而且同时编译会出问题！！！

**Comment by liuran001** [comment]
lr结尾的是我把多个不同版本的整合了，但是因为我最近没时间所以很久没更新。建议只选择一种，或者全部编译但是不内置进固件，然后自己手动安装看效果。

**Comment by iancchiu** [comment]
> lr最后的是我把多个不同版本的整合了，但是因为我最近没时间所以很久没更新。

早说嘛，我把所有编译了一遍，结果最后V3是我想要的。。。。。。。。。。。。。
